### ISSUE TITLE
[BUG] Please Confirm this big mistake - Chia-Net say's k30 & k31 are obsolete - If u follow this path it means replot ASAP

### ISSUE THREAD

**Issue by room101-dev** [HiveProject2021/chives-blockchain#10]
**Describe the bug**
1- The new version V1.1.9 will be available on July 10, 2021 at 3PM (SEATTLE), when everyone will start digging from 0.
2- Update content:
  2.1- 0 pre-digging.
  2.2- 10% from each block, as community share.
  2.3- Plot size reduced to: K29/K30/K31.
  2.4- Fix the same problem with other CHIA connections.
3- Problems with synchronization during use: Due to the requirement of synchronization in the code: there must be a block with timestamp within 7 minutes. Due to the small network space in the early stage, the block speed is slow, so it may show no synchronization. But it does not affect mining.
4- Mining pools are not supported for now, but will be supported in the next version (Oct 2021).
5- We suggest you to delete the .chives and the original KEYS, and deploy it fresh.
**Expected behavior**

Please confirm the above is true? There is no indication on this github that these change are true.

**Comment by HiveProject2021** [comment]
The code is located in dev branch.
Not in the main branch.
