### ISSUE TITLE
No plots passing proof [BUG]

### ISSUE THREAD

**Issue by glukkon24** [HiveProject2021/chives-blockchain#13]
I have been mining for over an hour with a 31 minute expected window and have not had one plot pass yet?

**Comment by reall4uk** [comment]
I have the same problem.
plots are made, but the program does not see them ..

**Comment by JulaTheDonkey** [comment]
same here. failed to to pen plots. All of them. Wallet running for over 8 hours.

**Comment by JulaTheDonkey** [comment]
> Same here. Failed to to open plots. All of them. Wallet running for over 8 hours...

My mistake. Doesn't work with chia k32 plots. K29 plots are needed. Good luck with replotting!

**Comment by HiveProject2021** [comment]
THANKS
