### ISSUE TITLE
Plots don't connect to GUI. Say that plots are bad[BUG]

### ISSUE THREAD

**Issue by v873kaminskiy** [HiveProject2021/chives-blockchain#14]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by v873kaminskiy** [comment]
Windows

**Comment by HiveProject2021** [comment]
Do you have more detail, e.g. logs, snapshoots and so on.

**Comment by v873kaminskiy** [comment]
I add directory with plots, but GUI think that them bad. 
"Not found Plots
Caution, deleting these plots will delete them forever. Check that the storage devices are properly connected."
But in other forks this plots works good. This is OG plots

**Comment by v873kaminskiy** [comment]
@HiveProject2021  directory is added. But GUI say that plots are bad

**Comment by v873kaminskiy** [comment]
![image](https://user-images.githubusercontent.com/16736051/125253300-f3d18880-e301-11eb-90ef-3a352ca8128a.png)

**Comment by v873kaminskiy** [comment]
![image](https://user-images.githubusercontent.com/16736051/125253409-0e0b6680-e302-11eb-81a8-a18b469f8486.png)

**Comment by v873kaminskiy** [comment]
I have 67Tb, but none of plots don't succecfully caonnected.

**Comment by v873kaminskiy** [comment]
Nodes works. After adding nodes is synced. But with plots the same

**Comment by JulaTheDonkey** [comment]
> Nodes works. After adding nodes is synced. But with plots the same

Hi, man! I made the same mistake yesterday. Expected to work with chia K32 plots. But it doesn't. It's different from the other forks. You have to replot k29 plots. Good luck! :)

**Comment by HiveProject2021** [comment]
Only support K29 30 31, Not support K32.
