### ISSUE TITLE
[BUG] Farmer RPC port 9759 conflict with Equality

### ISSUE THREAD

**Issue by kiote99** [HiveProject2021/chives-blockchain#15]
**Describe the bug**
In the config.yaml:

`Farmer:
...
  rpc_port: 9759`

Port 9759 conflicts with Equality's Farmer rpc_port (also 9759)
https://github.com/Equality-Network/equality-blockchain

**To Reproduce**

1. Install and run Equality and Chives farmers on the same host
2. Try to run both farmers at the same time

**Expected behavior**
Run both equality and chives farmers side by side

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Comment by HiveProject2021** [comment]
This port we used it first.
So we don't plan to change it.
