### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tinphan76123** [HiveProject2021/chives-blockchain#19]
Hi every one,
My name is TinPhan. 
I have issue about Chives 1.1.902 ( Electron 11.4.3, Chrome 87.0.4208.140, Node 12.18.3, V8: 8.7.220.31)
I can''t synchronization ( about 36 house), my app can''t sync, 
I can''t connec full Node status, blocks and connect to other peers.
![Capturesa](https://user-images.githubusercontent.com/84498970/129450317-aa67e8d8-ae3b-4b6c-93a7-993ef461f598.PNG)

tks

**Comment by dahaiyu82** [comment]
you can get help by visiting this address
https://penny-faucets-for-chia-forks.net/peers/#Chives-XCC

**Comment by Ciuffospecial** [comment]
same issue. i have other forks gui runing, chia gui running, hpool xproxy running and hpool mining program running. 
I tried to just let chieves start fas first but nothing changed

**Comment by HiveProject2021** [comment]
Any logs?

**Comment by onegoku** [comment]
I will close this one. You need to end all chives processes before starting it again. But this is now very old version, try the 1.2.11.
