### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zaphrodbblbrx** [HiveProject2021/chives-blockchain#22]
### What happened?

When I tried to install the current version of Chives Blockchain, on install it hangs before the screen that would allow key selection

When I open Dev tools; I see the following error

I'm unable to install Chives blockchain on my 2nd PC (win 10 pro) and the upgrade failed on my current farmer running 1.2.111

Please also re post the previous version, there are others having this issue (on reddit, the FB group ect) with the current version

i've left it running for 3 days, rebooted, deleted all the chives files and tried again ect.

thanks for your time

### Version

0.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
﻿
electron/js2c/renderer_init.js:65 Uncaught (in promise) Error: Error invoking remote method 'getConfig': YAMLException: duplicated mapping key (1037:3)

 1034 | 
 1035 |   # Allow connecting to remote p ...
 1036 | 
 1037 |   connect_to_unknown_peers: True
----------^
 1038 | 
 1039 | 
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:65)
```

**Comment by zaphrodbblbrx** [comment]
I forgot to mention, the GUI window says "Loading Configuration"

**Comment by zaphrodbblbrx** [comment]
![Chives GUI Error](https://user-images.githubusercontent.com/84676603/184687788-77557080-2ae0-40c4-9971-695bdeb9d6b6.png)

This is the error I get when i close out. its reproducable on both machines

**Comment by Kelcyo** [comment]
I get the same error on several machines, both with Windows 11 and Windows 10...
What is the solution?
Does anyone have the installer of a previous version that is working perfectly?

**Comment by zcomputerwiz** [comment]
This was addressed in a recent commit, and the next release will not have the problem.

In the meantime, please edit the config ( located in `C:\Users\yournamehere\.chives\mainnet\config\config.yaml` ).
Use a text editor and search for

`Allow connecting to remote peers for sync`

comment out the line below it (  connect_to_unknown_peers: True ) using `#`

```
  # Allow connecting to remote peers for sync
  connect_to_unknown_peers: True
```

It should look like this when finished.
```
  # Allow connecting to remote peers for sync
  # connect_to_unknown_peers: True
```

**Comment by Kelcyo** [comment]
Great, for the tip.

This wouldn't be the right place for this next difficulty, but it's where someone can help...
Where to find a faucet, the official page does not work correctly..

**Comment by TheBSMedia** [comment]
> Great, for the tip.
> 
> This wouldn't be the right place for this next difficulty, but it's where someone can help... Where to find a faucet, the official page does not work correctly..

Join the official discord server and there is a Faucet channel.

**Comment by zcomputerwiz** [comment]
Fixed with https://github.com/HiveProject2021/chives-blockchain/commit/6c55f9780a70f53988a8237c2f11d6b920cc1b5e
