### ISSUE TITLE
wallet not synced

### ISSUE THREAD

**Issue by sipeneco** [HiveProject2021/chives-blockchain#28]
I have chives blockchain for about 2 weeks, I have at this moment 136 plots k-29. this polts are farming for about a week, and my status is synced, but wallet isn't I don't know why? Today I have 0 XCC..
Something is wrong!!!

Why my wallet isn't synced?

**Comment by zackclark70** [comment]
feel free to hop in the discord and we can help trouble shoot

**Comment by Deniskok** [comment]
I have such a problem.
node is not synchronized, wallet is not synchronized!
what to do?

**Comment by Artur-01** [comment]
Не сихронизируется кошелек!!!!!

**Comment by IT2core** [comment]
I have same issue couple of weeks. how can i fix it?
![image](https://user-images.githubusercontent.com/6873720/145889631-63451d3f-bef4-46a4-a429-bed77e3ec6a0.png)

**Comment by IT2core** [comment]
any update in this case?
