### ISSUE TITLE
[BUG] Remote harvester info missing at farm summary

### ISSUE THREAD

**Issue by nbayaman** [HiveProject2021/chives-blockchain#32]
**Describe the bug**
No harvester information at farm summary

**To Reproduce**

1. Copied CA directory from full node machine to harvester machine
2. Inited harvester with the ca dir
3. Set farmer_peer: host: at line 171 in config.yaml
4. Started harvester, which seems to be working fine:
`2021-09-07T14:55:02.380 harvester chives.harvester.harvester: INFO 1 plots were eligible for farming dce5d4653d... Found 0 proofs. Time: 0.05566 s. Total 176 plots 2021-09-07T14:55:10.755 harvester chives.harvester.harvester: INFO 1 plots were eligible for farming dce5d4653d... Found 0 proofs. Time: 0.13775 s. Total 176 plots
`My full_node machine accepts connection from the harvester:
`tcp 0 0 65.49.80.**:9647 66.160.206.**:47684 ESTABLISHED 4813/chives_farmer
`
However, I don't see anything about the harvester when I check farm summary:
_chives farm summary
Farming status: Farming
Total chives farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Farmer Reward: 0.0
Pool Reward: 0.0
Plot count: 0
Total size of plots: 0.000 MiB
Estimated network space: 48.763 PiB
Expected time to win: Never (no plots)_

**Expected behavior**
Farm summary at full node machine should show connected harvester information

**Desktop (please complete the following information):**

- OS: Ubuntu Server 20.04
- CPU: 4 cpu VPS

**Comment by nbayaman** [comment]
The harvester seems to be working since I've got first block reward of 180 coins:

_chives farm summary
Farming status: Farming
Total chives farmed: 180.0
User transaction fees: 0.0
Block rewards: 180.0
Last height farmed: 2929**
Farmer Reward: 22.5
Pool Reward: 157.5
Plot count: 0
Total size of plots: 0.000 MiB
Estimated network space: 54.364 PiB
Expected time to win: Never (no plots)
Note: log into your key using 'chives wallet show' to see rewards for each key_

And still no information about the harvester at the full node machine.

**Comment by LocoSlug** [comment]
@nbayaman 
This feature was added into chia 1.2.x and chives was forked at version 1.1.7.

I forked chives and ported the harvester feature over from chia, seems to work but I'm not a trained developer.

**Comment by ichimars** [comment]
same issue… total plot size does not include plots from remote harvesters
