### ISSUE TITLE
[BUG] 25 words instead of 24 when creating a new private key

### ISSUE THREAD

**Issue by harambasapp** [HiveProject2021/chives-blockchain#34]
Describe the bug
I was playing around with adding a new wallet to my chia. I clicked on "Create new private key" but instead of 24 fields with 24 words, I saw 25 of them.

To Reproduce

Click on the "Create new private key"
go back
Click on the "Create new private key"
go back
Click on the "Create new private key"
go back
Click on the "Create new private key"
go back
Click on the "Import from mnemonic (24 words)"
go back
Click on the "Create new private key"
go back
Click on the "Create new private key"
go back
Click on the "Create new private key"
That additional 25. field should appear
Expected behavior
As I know there should always be 24 words for mnemonic

Desktop

OS: Windows 10 PRO
OS Version: 21H1
OS Build: 19043.1202
CPU: Ryzen 7 3700x

Additional context
Please check the video I have sent to you in the zip file.
Added steps for reproducing the issue are not 100% sure. It may depend on how much times do you have to click on these buttons and to go back.
[chives w01.zip](https://github.com/HiveProject2021/chives-blockchain/files/7147505/chives.w01.zip)
![chives 25words01 marked](https://user-images.githubusercontent.com/90500744/132942517-308e654e-1d2c-4d9f-84ff-818f78b2f921.PNG)

**Comment by LocoSlug** [comment]
It's fixed in chia currently.

https://github.com/Chia-Network/chia-blockchain-gui/commit/6edcd4878aacc5e561c2033023a3ddd758e00c23
