### ISSUE TITLE
bash: ./activate: No such file or directory

### ISSUE THREAD

**Issue by JasonUK786** [HiveProject2021/chives-blockchain#35]
Installing Chives, when I try `. ./activate `I get the error saying ./activate: No such file or directory.

How do I correct this?

**Comment by LocoSlug** [comment]
Maybe post a screen shot and we'll see if we can help.

**Comment by JasonUK786** [comment]
> Maybe post a screen shot and we'll see if we can help.

I can't get it all in a screenshot but see below the transcript from terminal window: 

`ajazpi@AjazPi:~$ cd
ajazpi@AjazPi:~$ sudo rm -rf ~/chives-blockchain
[sudo] password for ajazpi: 
ajazpi@AjazPi:~$ git clone -b dev https://github.com/HiveProject2021/chives-blockchain.git
Cloning into 'chives-blockchain'...
remote: Enumerating objects: 50733, done.
remote: Total 50733 (delta 0), reused 0 (delta 0), pack-reused 50733
Receiving objects: 100% (50733/50733), 22.19 MiB | 9.04 MiB/s, done.
Resolving deltas: 100% (39201/39201), done.
ajazpi@AjazPi:~$ cd chives-blockchain
ajazpi@AjazPi:~/chives-blockchain$ sh install.sh
apt-get is /usr/bin/apt-get
Submodule 'mozilla-ca' (https://github.com/Chia-Network/mozilla-ca.git) registered for path 'mozilla-ca'
Cloning into '/home/ajazpi/chives-blockchain/mozilla-ca'...
Submodule path 'mozilla-ca': checked out '6e8c42b3ef7d4ded22a994f9886e63f0060020bd'
Installing on Ubuntu 21.04 or newer.
Hit:1 http://deb.anydesk.com all InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease
Get:3 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease [115 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports hirsute-backports InRelease [101 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease [110 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports hirsute/main armhf Packages [1,348 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages [1,025 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages [1,025 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages [1,025 kB]
Ign:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports hirsute/restricted i386 Packages
Ign:12 http://ports.ubuntu.com/ubuntu-ports hirsute/universe i386 Packages
Ign:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages
Get:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages [189 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages [189 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages [189 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages [189 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages [189 kB]
Ign:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages
Get:20 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main arm64 DEP-11 Metadata [93.8 kB]
Ign:21 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/restricted i386 Packages
Ign:22 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe i386 Packages
Get:23 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe arm64 DEP-11 Metadata [55.1 kB]
Ign:24 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/multiverse i386 Packages
Ign:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports hirsute/restricted i386 Packages
Ign:12 http://ports.ubuntu.com/ubuntu-ports hirsute/universe i386 Packages
Ign:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages
Ign:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages
Ign:21 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/restricted i386 Packages
Ign:22 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe i386 Packages
Ign:24 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/multiverse i386 Packages
Ign:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports hirsute/restricted i386 Packages
Ign:12 http://ports.ubuntu.com/ubuntu-ports hirsute/universe i386 Packages
Get:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages [130 kB]
Ign:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages
Ign:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages
Ign:21 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/restricted i386 Packages
Ign:22 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe i386 Packages
Ign:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages
Get:27 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe arm64 DEP-11 Metadata [9,344 B]
Ign:24 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/multiverse i386 Packages
Ign:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports hirsute/restricted i386 Packages
Ign:12 http://ports.ubuntu.com/ubuntu-ports hirsute/universe i386 Packages
Ign:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages
Ign:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages
Ign:21 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/restricted i386 Packages
Ign:22 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe i386 Packages
Ign:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages
Ign:24 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/multiverse i386 Packages
Ign:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports hirsute/restricted i386 Packages
Ign:12 http://ports.ubuntu.com/ubuntu-ports hirsute/universe i386 Packages
Ign:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages
Ign:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages
Ign:21 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/restricted i386 Packages
Ign:22 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe i386 Packages
Get:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages [2,706 B]
Get:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages [2,706 B]
Get:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages [2,706 B]
Get:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages [2,706 B]
Ign:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages
Ign:24 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/multiverse i386 Packages
Err:7 http://ports.ubuntu.com/ubuntu-ports hirsute/main i386 Packages
  404  Not Found [IP: 91.189.91.38 80]
Ign:11 http://ports.ubuntu.com/ubuntu-ports hirsute/restricted i386 Packages
Ign:32 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main i386 Packages
Get:33 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main arm64 DEP-11 Metadata [7,964 B]
Ign:34 http://ports.ubuntu.com/ubuntu-ports hirsute-security/restricted i386 Packages
Ign:35 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe i386 Packages
Get:36 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe arm64 DEP-11 Metadata [3,864 B]
Ign:37 http://ports.ubuntu.com/ubuntu-ports hirsute-security/multiverse i386 Packages
Ign:12 http://ports.ubuntu.com/ubuntu-ports hirsute/universe i386 Packages
Ign:13 http://ports.ubuntu.com/ubuntu-ports hirsute/multiverse i386 Packages
Err:14 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/main i386 Packages
  404  Not Found [IP: 91.189.91.38 80]
Ign:21 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/restricted i386 Packages
Ign:22 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/universe i386 Packages
Ign:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages
Ign:24 http://ports.ubuntu.com/ubuntu-ports hirsute-updates/multiverse i386 Packages
Ign:32 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main i386 Packages
Ign:34 http://ports.ubuntu.com/ubuntu-ports hirsute-security/restricted i386 Packages
Ign:35 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe i386 Packages
Ign:37 http://ports.ubuntu.com/ubuntu-ports hirsute-security/multiverse i386 Packages
Ign:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages
Ign:32 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main i386 Packages
Ign:34 http://ports.ubuntu.com/ubuntu-ports hirsute-security/restricted i386 Packages
Ign:35 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe i386 Packages
Ign:37 http://ports.ubuntu.com/ubuntu-ports hirsute-security/multiverse i386 Packages
Err:26 http://ports.ubuntu.com/ubuntu-ports hirsute-backports/universe i386 Packages
  404  Not Found [IP: 91.189.91.38 80]
Ign:32 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main i386 Packages
Ign:34 http://ports.ubuntu.com/ubuntu-ports hirsute-security/restricted i386 Packages
Ign:35 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe i386 Packages
Ign:37 http://ports.ubuntu.com/ubuntu-ports hirsute-security/multiverse i386 Packages
Ign:32 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main i386 Packages
Ign:34 http://ports.ubuntu.com/ubuntu-ports hirsute-security/restricted i386 Packages
Ign:35 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe i386 Packages
Ign:37 http://ports.ubuntu.com/ubuntu-ports hirsute-security/multiverse i386 Packages
Err:32 http://ports.ubuntu.com/ubuntu-ports hirsute-security/main i386 Packages
  404  Not Found [IP: 91.189.91.38 80]
Ign:34 http://ports.ubuntu.com/ubuntu-ports hirsute-security/restricted i386 Packages
Ign:35 http://ports.ubuntu.com/ubuntu-ports hirsute-security/universe i386 Packages
Ign:37 http://ports.ubuntu.com/ubuntu-ports hirsute-security/multiverse i386 Packages
Fetched 496 kB in 8s (61.7 kB/s)                                                                            
Reading package lists... Done
N: Skipping acquisition of configured file 'main/binary-arm64/Packages', as repository 'http://deb.anydesk.com all InRelease' doesn't support architecture 'arm64'
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/hirsute/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/hirsute-updates/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/hirsute-backports/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/hirsute-security/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.38 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
ajazpi@AjazPi:~/chives-blockchain$ . ./activate
bash: ./activate: No such file or directory
ajazpi@AjazPi:~/chives-blockchain$ sh install-gui.sh
This requires the chives python virtual environment.
Execute '. ./activate' before running.
ajazpi@AjazPi:~/chives-blockchain$ cd`

**Comment by deniztas10** [comment]
I have some issue. Please help we.
