### ISSUE TITLE
[BUG]enter the wrong address in the transfer, transfer Xcc to XCH's address. This XCH address will be converted to an unknown Xcc address.

### ISSUE THREAD

**Issue by linzhiqiang0514** [HiveProject2021/chives-blockchain#48]
**Describe the bug**
If I enter the wrong address in the transfer, transfer Xcc to XCH's address. This XCH address will be converted to an unknown Xcc address. 
I have done such a thing once on October 17.
Same address.

Can I get it back?

**To Reproduce**
use xch address for: xch1a83ce5uxkr94ek9nea3aj0rs8cnj4dafkx7ftf49jmhfndpgc8vqdsmxyy
convert xcc address: xcc1a83ce5uxkr94ek9nea3aj0rs8cnj4dafkx7ftf49jmhfndpgc8vqt80g5f

**Expected behavior**
Can I get it back?

**Screenshots**
![image](https://user-images.githubusercontent.com/8164566/139715343-289e8354-f36a-4ae8-9812-bc9966e3b81a.png)

![image](https://user-images.githubusercontent.com/8164566/139715315-452d24cb-35ae-417b-b0c0-a8fcae202114.png)

**Comment by onegoku** [comment]
I don't think there is a way to get it back. It was sent to some random xcc wallet...
