### ISSUE TITLE
[BUG] No winning with over 1000 plots

### ISSUE THREAD

**Issue by ichimars** [HiveProject2021/chives-blockchain#50]
Having 1560 plots now no winning since 06 Nov. Fully synced and Farming status ok (green) in Windows gui.
My Farming portal shows 0 plots  and Offlline statuses.

**Comment by dsykes16** [comment]
Check your `debug.log` file in `~/.chives/mainnet/logs/debug.log`. The GUI isn't known for being the most responsive on Chia or any of its forks, this one included. Personally I use the CLI for everything, it's just more stable and flexible.

I can also add that, at least on Linux, there appear to be no bugs with farming over 5,000 plots on a single farmer/harvester node.

**Comment by john-yan** [comment]
Hey, I have 1467 plots and I am using command line. Running into same issue here. `debug.log` seems ok, no errors were found. All the harvester response times are less than 3s. and I could not win anything since Nov 7. Please advice. Thanks.

**Comment by ExcaIibur** [comment]
When I had this same problem, it was because I hadn't entered the addresses properly. Make sure that you get the correct addresses in your command line.

**Comment by defoxpcs** [comment]
Same problem here. I got stucked in no gains about 3-4 days, then I reinstalled and re-sync the app. Result: 2 gains in 1 day. And now seems I'm stucked again, no gain about 3 days.. ~ 1500 plots

**Comment by jeromflo** [comment]
same problem, Sice the last 3 weeks, didn't win any. And misteriously close the gui. Someone can help? I try to reinstall with delete .chives and AppLocal

**Comment by jaxman19-99** [comment]
Any updates on this?

**Comment by onegoku** [comment]
You should all try the new version 1.2.11. But we can't really help you with the no-wins problem. It is random and if you are getting proof attempts and no errors in the log, then there is nothing we can fix.

**Comment by ExcaIiburOfLegend** [comment]
i had supreme issues with getting chives to work.
i took note of my 24 word key, making sure that i had it 100% correct.
then i formatted my hard drive, trying to get windows 11 to work, windows 10 worked, then windows 11 updated. 
it was really weird. however formatting my hard drive, then reinstalling my operating system, fixed the issue. s.
