### ISSUE TITLE
Gui work very slow

### ISSUE THREAD

**Issue by stefy6667** [HiveProject2021/chives-blockchain#52]
The gui is open very slow and with over 1k plots take over 2 hours to read it

**Comment by NordicSnowman** [comment]
You probably need to check your drives and/or network shares.
Open config.yaml and remove all drives, restart gui. Then add one drive at the time and look where it starts to slow down, and you have probably found the drive causing it. 
Network shares can cause high seek times too.
Look in debug.log after errors or very high lookup times.

**Comment by onegoku** [comment]
Hey, in the newest version 1.2.11 this problem is gone. GUI should be now faster.
