### ISSUE TITLE
[BUG] Remote harvester don't show

### ISSUE THREAD

**Issue by mcsham** [HiveProject2021/chives-blockchain#56]
**Describe the bug**
plots on the remote harvester are not visible on the main node. The GUI shows that the remote harvesters have joined, but the number of plots has not changed. In the console, the farm only shows local plots.

**To Reproduce**

Remote server:
```
serv@serv:~/chia/chives-blockchain$ . ./activate 
(venv) serv@serv:~/chia/chives-blockchain$ chives init
Chives directory /home/serv/.chives/mainnet
/home/serv/.chives/mainnet already exists, no migration action taken
(venv) serv@serv:~/chia/chives-blockchain$ chives init -c ~/chia/chives_key/
Deleting your OLD CA in /home/serv/.chives/mainnet/config/ssl/ca
Copying your CA from /home/serv/chia/chives_key to /home/serv/.chives/mainnet/config/ssl/ca
/home/serv/.chives/mainnet/config/ssl/ca/private_ca.crt
/home/serv/.chives/mainnet/config/ssl/ca/chives_ca.crt
/home/serv/.chives/mainnet/config/ssl/ca/private_ca.key
/home/serv/.chives/mainnet/config/ssl/ca/chives_ca.key
Found private CA in /home/serv/.chives/mainnet, using it to generate TLS certificates
(venv) serv@serv:~/chia/chives-blockchain$ chives plots show
Directories where plots are being searched for:
Note that subdirectories must be added manually
Add with 'chives plots add -d [dir]' and remove with 'chives plots remove -d [dir]' Scan and check plots with 'chives plots check'

/media/1/chives
/media/2/chives
/media/3/chives
/media/4/chives
/media/5/chives
/media/6/chives
/media/7/chives
/media/8/chives
/media/9/chives
/media/10/chives
/media/11/chives
/media/12/chives
/media/13/chives
/media/14/chives
/media/ssd/rez/chives
(venv) serv@serv:~/chia/chives-blockchain$ chives configure --set-farmer-peer 192.168.1.100:9647
Farmer peer updated, make sure your harvester has the proper cert installed
Restart any running chives services for changes to take effect
(venv) serv@serv:~/chia/chives-blockchain$ chives start harvester -r
chives_harvester: stopped
chives_harvester: started
```

**Screenshots**
![image](https://user-images.githubusercontent.com/40900923/142773406-01e94b74-2c12-43f9-bf46-f436d971f8b6.png)
it's local count plots
![image](https://user-images.githubusercontent.com/40900923/142773422-b35cf862-0f41-472e-ae8a-daf9e5b4bc8d.png)
in console
![image](https://user-images.githubusercontent.com/40900923/142773469-2b8689be-5cfe-4e33-a844-e25fb1b3e9a2.png)

**Desktop (please complete the following information):**
- OS: Linux
- OS Ubuntu 20

**Comment by Andrey987654321** [comment]
НордикСнегов прошу помочь мне, я Поставил анализатор Chia Log.... Показало  11% Здоровья. В чем дело?
![Безымянный](https://user-images.githubusercontent.com/95348465/144219337-5d966409-8a0c-416f-90f2-bc3b65fceba9.jpg)

**Comment by onegoku** [comment]
Hey, in the newest version 1.2.11 the harvesters will show like expected.
