### ISSUE TITLE
Chives doesn't want to install on raspberry..

### ISSUE THREAD

**Issue by dognjeno** [HiveProject2021/chives-blockchain#74]
(venv) pi@raspberrypi:~/chives-blockchain $ sh install-gui.sh
apt-get is /usr/bin/apt-get
Please install NODEJS&NPM manually

Installing on Ubuntu older than 20.04 LTS: Ugrading node.js to stable.
sudo: npm: command not found
(venv) pi@raspberrypi:~/chives-blockchain $

Every. Single. Time. 
No matter what OS I install. Oh, hey, .deb installer also doesn't work. (Python is v3.9)

**Comment by mygitchives** [comment]
I got this problem as well.
The solution is making sure you have the latest npm installed globally and the latest electron as well.

Something like:
`npm install -g npm@latest`
`npm install -g electron@latest`

If not working, you may try to remove the global flag:
`npm install npm@latest`
`npm install electron@latest`

I did have this problem on Raspberry Pi and solved it.
I'm just not 100% sure to remember what I've done but it was along what I said above.

Good luck, let me know if it works.
