### ISSUE TITLE
[Bug] Broken linkage to the "mozzila-ca" submodule

### ISSUE THREAD

**Issue by ageorge95** [HiveProject2021/chives-blockchain#78]
### What happened?

The latest commit at the time of writing: c1111a79d7a1eb02a0bd2111307e266583bc67d1 has broken the linkage to the "mozzila-ca" submodule. The .gitmodules file is now empty whereas it should contain the submodule definition !

### Version

v1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
Exception in GET /pool_info https://pool.chivespool.com, [Errno 2] No such file or directory

caused by

def get_mozilla_ca_crt() -> str:
    mozilla_path = Path(__file__).parent.parent.parent.absolute() / "mozilla-ca/cacert.pem"
    return str(mozilla_path)

caused by the missing submodule "mozilla-ca"
```

**Comment by sergkog** [comment]
cp chives-blockchain/mozilla-ca-main/cacert.pem chives-blockchain/mozilla-ca/cacert.pem

**Comment by ageorge95** [comment]
Issue fixed in https://github.com/HiveProject2021/chives-blockchain/commit/04ff2a9e5c90de0ee472128b5d637422a7ae5b52
